version: '3'
services:
  hugo_app:
    container_name: hugo_app
    build: 
      context: .
    volumes:
      - ./hugo:/hugo
    ports:
      - "1313:1313"
    tty: true
    # command: hugo server -D --bind="0.0.0.0"